### ISSUE TITLE
Unable to remove Newly added "Search H1B Sponsors" from left side of screen

### ISSUE THREAD

**Issue by AnujSt** [kart33k/UltimateH1BSponsorChecker#22]
Please remove this "Search H1B Sponsors" because of this I am unable to see content while applying to jobs and also it appears on while using LinkedIn learning

**Comment by kart33k** [comment]
Hi Can you please send a screenshot so I can align the button better.

**Comment by dnwjn** [comment]
> Hi Can you please send a screenshot so I can align the button better.

Besides realigning, it would also be great if we could disable it. It's a nice functionality, but I for example don't have a use for it currently.

**Comment by kart33k** [comment]
ok, disabled the search feature for now, will add ability to enable disable the feature and default will be disabled.
It should be released in a day.

**Comment by AnujSt** [comment]
Thank you!
