### ISSUE TITLE
Linkedin dark mode support

### ISSUE THREAD

**Issue by touseefbsb** [kart33k/UltimateH1BSponsorChecker#3]
First of all great plugin and really appreciate it.
**Feature Request** :
I use Linkedin website on my pc in dark mode, and the text of this plugin is hard to read on dark mode. if possible please can you fix it. Thanks

**Comment by kart33k** [comment]
thank you, will look into it.

**Comment by kart33k** [comment]
![image](https://user-images.githubusercontent.com/31315771/201572715-e39fa36b-de2b-4472-84f1-472c03896c50.png)

A version was deployed, please check it out,

**Comment by touseefbsb** [comment]
Yeah this looks great thanks
