### ISSUE TITLE
Cannot see badges on glassdoor

### ISSUE THREAD

**Issue by lhchen75** [kart33k/UltimateH1BSponsorChecker#4]
Dear developer, I saw on the introduction that this extension can be used on glassdoor. However, it does not work for my glassdoor. Is this website no longer supported anymore? Thank you for your answer!

**Comment by lhchen75** [comment]
Thank you for the prompt response!

**Comment by kart33k** [comment]
hello, new version is released and Badges are available on Glassdoor. Though extra info is not available Hopefully this helps a little.

**Comment by lhchen75** [comment]
Thank you sooooo much😄😄😄
