### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by s10mary** [kart33k/UltimateH1BSponsorChecker#50]
The H1B sponsor checker appears on UK job posts located in the United Kingdom either for Remote, Hybrid or On-site as "H1B Sponsor available" and this leaves me confused because I know very well that H1B is for the US availability of a sponsorship job

**Comment by kart33k** [comment]
Please disable the h1b sponsor when searching for UK jobs and disable UK
visa job sponsor when searching  US jobs.
